version: 2
# executors:
#   docker:
#     - image: circleci/node:lts
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    branchs:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - run:
          name: Install Dependence
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            git config user.name ${GH_NAME}
            git config user.name ${GH_EMAIL}
            npx gh-pages -d dist -r https://${GH_TOKEN}@github.com/ddiu8081/ChartFun.git -b master -m "uploaded newest dist."